In [2]:
import numpy as np

EX 1

In [4]:
payments = np.matrix('0.05,0.07,0; 0.05,0,0.06;1,1,1')
receiving = np.matrix('2250;1400;50000')
result = np.linalg.solve(payments,receiving)
result

matrix([[10000.],
        [25000.],
        [15000.]])

EX 2

In [5]:
iphones = np.matrix('-1,1,0; 1,0,-1; 1,1,1')
total = np.matrix('120; 100; 1328')
result = np.linalg.solve(iphones,total)
result

matrix([[436.],
        [556.],
        [336.]])

EX 3

In [3]:
odds = np.matrix('3,0,3; 6,0.25,0; 1,0.33,1')
res = np.matrix('1;1;1')
result = np.linalg.solve(odds,res)
result

matrix([[0.08249158],
        [2.02020202],
        [0.25084175]])

In [4]:
a = (1/result[0])
b = (1/result[1])
c = (1/result[2])

matrix([[3.98657718]])

In [5]:
a

matrix([[12.12244898]])

In [6]:
b

matrix([[0.495]])

In [7]:
c

matrix([[3.98657718]])

EX 4

In [14]:
x = np.matrix('1,1,1; 9,3,1; 1,-1,1')
y = np.matrix('12;54;2')
result = np.linalg.solve(x,y)
result

matrix([[4.],
        [5.],
        [3.]])

EX 5

In [19]:
def get_polynom(coords):
    n = len(coords)-1
    list_for_a = []
    list_for_b = []
    
    for x, y in coords:
        list_for_b.append(y)
        x_list = []
        for i in range(n+1):
            x_list.append(x**i)
        list_for_a. append(x_list)    
    
    a = np.array(list_for_a)
    b = np.array(list_for_b)
    
    return np.linalg.solve(a, b)

In [22]:
get_polynom([(1,6), (2,0), (10, 103)])

array([ 16.19444444, -12.29166667,   2.09722222])